export const typeOptions = [
  { text: "Krivični predmeti", value: "K" },
  { text: "Krivični predmeti - maloljetnici", value: "Km" },
  { text: "Parnični predmeti", value: "P" },
  { text: "Parnični predmeti - mala vrijednost", value: "Mal" },
  { text: "Privredni predmeti", value: "Ps" },
  { text: "Privredni predmeti - mala vrijednost", value: "Mals" },
  { text: "Vanparnični predmeti", value: "V" },
  { text: "Ostavinski predmeti", value: "O" },
  { text: "Izvršenje građansko", value: "I" },
  { text: "Izvršenje privredno", value: "Ip" },
  { text: "Stečajni predmeti", value: "St" },
  { text: "Likvidacioni predmeti", value: "L" },
  { text: "Upravni spor", value: "U" },
  { text: "Sudska uprava", value: "Su" },
  { text: "Deponiranje testamenta", value: "Pi" },
  { text: "Založno pravo", value: "Zzp" },
  { text: "Prekršajni predmeti", value: "Pr" },
  { text: "Radni sporovi", value: "Rs" },
  { text: "Zemljišnoknjižni predmeti", value: "Dn" },
  { text: "Registar pravnih lica", value: "Reg" },
  { text: "Knjiga položenih ugovora", value: "KPU" },
];
